export const SET_DATA_FROM_DB = "SET_DATA_FROM_DB";
export const CLEAR_DATA_FROM_DB = "CLEAR_DATA_FROM_DB";
export const OPEN_SCANNER = "OPEN_SCANNER";
export const CLOSE_SCANNER = "CLOSE_SCANNER";
export const SET_SCANNED_DATA = "SET_SCANNED_DATA";
export const CLEAR_SCANNED_DATA = "CLEAR_SCANNED_DATA";
